FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.9.1

RUN install_packages curl wget build-essential libelf-dev awscli bc flex libssl-dev python bison alsa-utils libportaudio2

COPY ./src /usr/src/app
WORKDIR /usr/src/app

RUN pip install sounddevice configparser numpy rx scipy

CMD ["python3", "/usr/src/app/test.py"]

