version: '2'
services:
  meter:
    build: .
    restart: always
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/debus/system_bus_socket"
